"""new fields in user model

Revision ID: 32754007e34f
Revises: dc83f61f81be
Create Date: 2019-12-05 22:11:40.561050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32754007e34f'
down_revision = 'dc83f61f81be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
